version: "3"

services:
  app:
    build: .
    image: mxchip-gifs
    container_name: mxchip-gifs
    command: node server.js
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
